<?php

declare(strict_types=1);

/*
 * This file is part of the UhifadhiLabs Patrol Module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Patrol\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * THE ELEVEN TABLES THIS MODULE OWNS, CREATED BY THE MODULE.
 *
 * A patrol and its track (the batches points arrive in, and the points), what
 * was seen on it (observations, their photographs and the amendments written
 * afterwards), the per-area observation taxonomy, the drone side (launch points
 * and flights) and the event log the handset syncs through. An installation
 * runs `doctrine:migrations:migrate` and writes none of this itself.
 *
 * THE DATE IS LATER THAN EVERY CORE VERSION, and that is what places it. A
 * version's identity is its full class name and the shipped comparator is a
 * strcmp over it, so with a namespace per package the order would be
 * alphabetical by package — `Uhifadhi\Bundle\...` before `Uhifadhi\Patrol\...`
 * only by luck. The core replaces the comparator with one that reads the
 * trailing YmdHis, so this file's 20260910044923 is what guarantees
 * `area_of_interest` and `team_user` exist before the constraints below name
 * them.
 *
 * @see vendor/uhifadhi/uhifadhi/src/Uhifadhi/Bundle/RegistryBundle/Version/VersionTimestampComparator.php
 * @see vendor/doctrine/migrations/src/Version/AlphabeticalComparator.php
 *
 * THE SEVEN FOREIGN KEYS THAT LEAVE THIS PACKAGE live here, in the module that
 * declares the relation, not in the core: `patrol_patrol.area_id` and
 * `patrol_taxonomy_kind.area_id` into AreaBundle's `area_of_interest`, and five
 * person columns — a patrol's lead and whoever holds it, an observation's
 * recorder, an amendment's author, an event's actor — into TeamBundle's
 * `team_user`. Photographs carry a storage KEY and no constraint: the storage
 * module owns no table for one to point at.
 *
 * Nothing here is destructive: every statement in up() creates. down() takes the
 * eleven tables back out, which is the schema rehearsal an upgrade is tested
 * with and not a data-safe undo.
 */
final class Version20260910044923 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Patrols, tracks, observations, photographs, taxonomy, flights and the sync event log';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE patrol_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, client_uuid UUID NOT NULL, kind VARCHAR(40) NOT NULL, at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, payload JSON NOT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, patrol_id INT NOT NULL, actor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AABB13CCE393C4 ON patrol_event (client_uuid)');
        $this->addSql('CREATE INDEX IDX_AABB13CCA7B49BA9 ON patrol_event (patrol_id)');
        $this->addSql('CREATE INDEX IDX_AABB13CC10DAF24A ON patrol_event (actor_id)');
        $this->addSql('CREATE TABLE patrol_flight (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, client_uuid UUID NOT NULL, sequence INT DEFAULT 1 NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, patrol_id INT NOT NULL, launch_point_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_18A64BC7E393C4 ON patrol_flight (client_uuid)');
        $this->addSql('CREATE INDEX IDX_18A64BC7A7B49BA9 ON patrol_flight (patrol_id)');
        $this->addSql('CREATE INDEX IDX_18A64BC7A495DAEF ON patrol_flight (launch_point_id)');
        $this->addSql('CREATE TABLE patrol_launch_point (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, client_uuid UUID NOT NULL, label VARCHAR(40) NOT NULL, name VARCHAR(120) DEFAULT NULL, position geometry(POINT,4326) NOT NULL, accuracy_m DOUBLE PRECISION DEFAULT NULL, satellites INT DEFAULT NULL, established_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, sector_type VARCHAR(255) NOT NULL, sector_radius_m DOUBLE PRECISION DEFAULT NULL, sector_polygon geometry(POLYGON,4326) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, patrol_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_29E0744AE393C4 ON patrol_launch_point (client_uuid)');
        $this->addSql('CREATE INDEX IDX_29E0744AA7B49BA9 ON patrol_launch_point (patrol_id)');
        $this->addSql('CREATE INDEX idx_patrol_launch_point_position_sp ON patrol_launch_point USING gist (position)');
        $this->addSql('CREATE INDEX idx_patrol_launch_point_sector_polygon_sp ON patrol_launch_point USING gist (sector_polygon)');
        $this->addSql('CREATE TABLE patrol_observation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, client_uuid UUID DEFAULT NULL, category VARCHAR(40) NOT NULL, note TEXT DEFAULT NULL, position geometry(POINT,4326) DEFAULT NULL, position_source VARCHAR(255) DEFAULT \'gps\' NOT NULL, accuracy_m DOUBLE PRECISION DEFAULT NULL, satellites INT DEFAULT NULL, photo_count INT DEFAULT 0 NOT NULL, launch_point_client_uuid UUID DEFAULT NULL, flight_client_uuid UUID DEFAULT NULL, logged_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, patrol_id INT NOT NULL, launch_point_id INT DEFAULT NULL, flight_id INT DEFAULT NULL, recorded_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_51A3A4E0D17F50A6 ON patrol_observation (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_51A3A4E0E393C4 ON patrol_observation (client_uuid)');
        $this->addSql('CREATE INDEX IDX_51A3A4E0A7B49BA9 ON patrol_observation (patrol_id)');
        $this->addSql('CREATE INDEX IDX_51A3A4E0A495DAEF ON patrol_observation (launch_point_id)');
        $this->addSql('CREATE INDEX IDX_51A3A4E091F478C5 ON patrol_observation (flight_id)');
        $this->addSql('CREATE INDEX IDX_51A3A4E0D05A957B ON patrol_observation (recorded_by_id)');
        $this->addSql('CREATE INDEX idx_patrol_observation_position_sp ON patrol_observation USING gist (position)');
        $this->addSql('CREATE TABLE patrol_observation_amendment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, kind VARCHAR(40) NOT NULL, body TEXT NOT NULL, superseded_value TEXT DEFAULT NULL, written_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, author_name VARCHAR(120) DEFAULT NULL, observation_id INT NOT NULL, photo_id INT DEFAULT NULL, author_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_282D403FD17F50A6 ON patrol_observation_amendment (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_282D403F7E9E4C8C ON patrol_observation_amendment (photo_id)');
        $this->addSql('CREATE INDEX idx_patrol_amendment_observation ON patrol_observation_amendment (observation_id, written_at)');
        $this->addSql('CREATE INDEX IDX_282D403F1409DD88 ON patrol_observation_amendment (observation_id)');
        $this->addSql('CREATE INDEX IDX_282D403FF675F31B ON patrol_observation_amendment (author_id)');
        $this->addSql('CREATE TABLE patrol_observation_photo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, client_uuid UUID NOT NULL, storage_path VARCHAR(255) NOT NULL, thumb_key VARCHAR(255) DEFAULT NULL, mime_type VARCHAR(100) DEFAULT NULL, byte_size INT DEFAULT NULL, taken_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, position geometry(POINT,4326) DEFAULT NULL, accuracy_m DOUBLE PRECISION DEFAULT NULL, from_amendment BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, observation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3FCCB83CE393C4 ON patrol_observation_photo (client_uuid)');
        $this->addSql('CREATE INDEX IDX_3FCCB83C1409DD88 ON patrol_observation_photo (observation_id)');
        $this->addSql('CREATE INDEX idx_patrol_observation_photo_position_sp ON patrol_observation_photo USING gist (position)');
        $this->addSql('CREATE TABLE patrol_patrol (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, client_uuid UUID DEFAULT NULL, type VARCHAR(40) NOT NULL, name VARCHAR(120) DEFAULT NULL, station VARCHAR(80) DEFAULT NULL, team VARCHAR(255) DEFAULT NULL, team_ranger_ids JSON NOT NULL, note TEXT DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, distance_km DOUBLE PRECISION DEFAULT NULL, source VARCHAR(255) NOT NULL, status VARCHAR(255) DEFAULT \'complete\' NOT NULL, discard_reason TEXT DEFAULT NULL, held_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, drone_id VARCHAR(80) DEFAULT NULL, mission VARCHAR(120) DEFAULT NULL, device_id VARCHAR(64) DEFAULT NULL, app_version VARCHAR(32) DEFAULT NULL, web_edited_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, track geometry(LINESTRING,4326) DEFAULT NULL, point_count INT DEFAULT NULL, gap_count INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, area_id INT NOT NULL, lead_id INT DEFAULT NULL, held_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D10A8EB8D17F50A6 ON patrol_patrol (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D10A8EB8E393C4 ON patrol_patrol (client_uuid)');
        $this->addSql('CREATE INDEX IDX_D10A8EB8BD0F409C ON patrol_patrol (area_id)');
        $this->addSql('CREATE INDEX IDX_D10A8EB855458D ON patrol_patrol (lead_id)');
        $this->addSql('CREATE INDEX IDX_D10A8EB85EEE5820 ON patrol_patrol (held_by_id)');
        $this->addSql('CREATE INDEX idx_patrol_patrol_track_sp ON patrol_patrol USING gist (track)');
        $this->addSql('CREATE TABLE patrol_taxonomy_kind (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, code VARCHAR(40) NOT NULL, label VARCHAR(80) NOT NULL, position INT DEFAULT 0 NOT NULL, active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, area_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_999CC616D17F50A6 ON patrol_taxonomy_kind (uuid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_patrol_tx_kind_area_code ON patrol_taxonomy_kind (area_id, code)');
        $this->addSql('CREATE INDEX IDX_999CC616BD0F409C ON patrol_taxonomy_kind (area_id)');
        $this->addSql('CREATE TABLE patrol_taxonomy_subcategory (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, code VARCHAR(60) NOT NULL, label VARCHAR(80) NOT NULL, position INT DEFAULT 0 NOT NULL, active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, kind_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_72313009D17F50A6 ON patrol_taxonomy_subcategory (uuid)');
        $this->addSql('CREATE INDEX IDX_7231300930602CA9 ON patrol_taxonomy_subcategory (kind_id)');
        $this->addSql('CREATE TABLE patrol_track_batch (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, batch_key VARCHAR(120) NOT NULL, point_count INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, patrol_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_patrol_track_batch_key ON patrol_track_batch (batch_key)');
        $this->addSql('CREATE INDEX IDX_1C298F73A7B49BA9 ON patrol_track_batch (patrol_id)');
        $this->addSql('CREATE TABLE patrol_track_point (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position geometry(POINT,4326) NOT NULL, recorded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, accuracy_m DOUBLE PRECISION DEFAULT NULL, satellites INT DEFAULT NULL, elevation_m DOUBLE PRECISION DEFAULT NULL, speed_ms DOUBLE PRECISION DEFAULT NULL, patrol_id INT NOT NULL, batch_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_patrol_track_point_patrol_time ON patrol_track_point (patrol_id, recorded_at)');
        $this->addSql('CREATE INDEX IDX_53872E83A7B49BA9 ON patrol_track_point (patrol_id)');
        $this->addSql('CREATE INDEX IDX_53872E83F39EBE7A ON patrol_track_point (batch_id)');
        $this->addSql('CREATE INDEX idx_patrol_track_point_position_sp ON patrol_track_point USING gist (position)');
        $this->addSql('ALTER TABLE patrol_event ADD CONSTRAINT FK_AABB13CCA7B49BA9 FOREIGN KEY (patrol_id) REFERENCES patrol_patrol (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_event ADD CONSTRAINT FK_AABB13CC10DAF24A FOREIGN KEY (actor_id) REFERENCES team_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_flight ADD CONSTRAINT FK_18A64BC7A7B49BA9 FOREIGN KEY (patrol_id) REFERENCES patrol_patrol (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_flight ADD CONSTRAINT FK_18A64BC7A495DAEF FOREIGN KEY (launch_point_id) REFERENCES patrol_launch_point (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_launch_point ADD CONSTRAINT FK_29E0744AA7B49BA9 FOREIGN KEY (patrol_id) REFERENCES patrol_patrol (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_observation ADD CONSTRAINT FK_51A3A4E0A7B49BA9 FOREIGN KEY (patrol_id) REFERENCES patrol_patrol (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_observation ADD CONSTRAINT FK_51A3A4E0A495DAEF FOREIGN KEY (launch_point_id) REFERENCES patrol_launch_point (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_observation ADD CONSTRAINT FK_51A3A4E091F478C5 FOREIGN KEY (flight_id) REFERENCES patrol_flight (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_observation ADD CONSTRAINT FK_51A3A4E0D05A957B FOREIGN KEY (recorded_by_id) REFERENCES team_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_observation_amendment ADD CONSTRAINT FK_282D403F1409DD88 FOREIGN KEY (observation_id) REFERENCES patrol_observation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_observation_amendment ADD CONSTRAINT FK_282D403F7E9E4C8C FOREIGN KEY (photo_id) REFERENCES patrol_observation_photo (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_observation_amendment ADD CONSTRAINT FK_282D403FF675F31B FOREIGN KEY (author_id) REFERENCES team_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_observation_photo ADD CONSTRAINT FK_3FCCB83C1409DD88 FOREIGN KEY (observation_id) REFERENCES patrol_observation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_patrol ADD CONSTRAINT FK_D10A8EB8BD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_patrol ADD CONSTRAINT FK_D10A8EB855458D FOREIGN KEY (lead_id) REFERENCES team_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_patrol ADD CONSTRAINT FK_D10A8EB85EEE5820 FOREIGN KEY (held_by_id) REFERENCES team_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_taxonomy_kind ADD CONSTRAINT FK_999CC616BD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_taxonomy_subcategory ADD CONSTRAINT FK_7231300930602CA9 FOREIGN KEY (kind_id) REFERENCES patrol_taxonomy_kind (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_track_batch ADD CONSTRAINT FK_1C298F73A7B49BA9 FOREIGN KEY (patrol_id) REFERENCES patrol_patrol (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_track_point ADD CONSTRAINT FK_53872E83A7B49BA9 FOREIGN KEY (patrol_id) REFERENCES patrol_patrol (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_track_point ADD CONSTRAINT FK_53872E83F39EBE7A FOREIGN KEY (batch_id) REFERENCES patrol_track_batch (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE patrol_event DROP CONSTRAINT FK_AABB13CCA7B49BA9');
        $this->addSql('ALTER TABLE patrol_event DROP CONSTRAINT FK_AABB13CC10DAF24A');
        $this->addSql('ALTER TABLE patrol_flight DROP CONSTRAINT FK_18A64BC7A7B49BA9');
        $this->addSql('ALTER TABLE patrol_flight DROP CONSTRAINT FK_18A64BC7A495DAEF');
        $this->addSql('ALTER TABLE patrol_launch_point DROP CONSTRAINT FK_29E0744AA7B49BA9');
        $this->addSql('ALTER TABLE patrol_observation DROP CONSTRAINT FK_51A3A4E0A7B49BA9');
        $this->addSql('ALTER TABLE patrol_observation DROP CONSTRAINT FK_51A3A4E0A495DAEF');
        $this->addSql('ALTER TABLE patrol_observation DROP CONSTRAINT FK_51A3A4E091F478C5');
        $this->addSql('ALTER TABLE patrol_observation DROP CONSTRAINT FK_51A3A4E0D05A957B');
        $this->addSql('ALTER TABLE patrol_observation_amendment DROP CONSTRAINT FK_282D403F1409DD88');
        $this->addSql('ALTER TABLE patrol_observation_amendment DROP CONSTRAINT FK_282D403F7E9E4C8C');
        $this->addSql('ALTER TABLE patrol_observation_amendment DROP CONSTRAINT FK_282D403FF675F31B');
        $this->addSql('ALTER TABLE patrol_observation_photo DROP CONSTRAINT FK_3FCCB83C1409DD88');
        $this->addSql('ALTER TABLE patrol_patrol DROP CONSTRAINT FK_D10A8EB8BD0F409C');
        $this->addSql('ALTER TABLE patrol_patrol DROP CONSTRAINT FK_D10A8EB855458D');
        $this->addSql('ALTER TABLE patrol_patrol DROP CONSTRAINT FK_D10A8EB85EEE5820');
        $this->addSql('ALTER TABLE patrol_taxonomy_kind DROP CONSTRAINT FK_999CC616BD0F409C');
        $this->addSql('ALTER TABLE patrol_taxonomy_subcategory DROP CONSTRAINT FK_7231300930602CA9');
        $this->addSql('ALTER TABLE patrol_track_batch DROP CONSTRAINT FK_1C298F73A7B49BA9');
        $this->addSql('ALTER TABLE patrol_track_point DROP CONSTRAINT FK_53872E83A7B49BA9');
        $this->addSql('ALTER TABLE patrol_track_point DROP CONSTRAINT FK_53872E83F39EBE7A');
        $this->addSql('DROP TABLE patrol_event');
        $this->addSql('DROP TABLE patrol_flight');
        $this->addSql('DROP TABLE patrol_launch_point');
        $this->addSql('DROP TABLE patrol_observation');
        $this->addSql('DROP TABLE patrol_observation_amendment');
        $this->addSql('DROP TABLE patrol_observation_photo');
        $this->addSql('DROP TABLE patrol_patrol');
        $this->addSql('DROP TABLE patrol_taxonomy_kind');
        $this->addSql('DROP TABLE patrol_taxonomy_subcategory');
        $this->addSql('DROP TABLE patrol_track_batch');
        $this->addSql('DROP TABLE patrol_track_point');
    }
}
