<?php

declare(strict_types=1);

/*
 * This file is part of the UhifadhiLabs Patrol Module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Patrol\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * THE WORDS BECOME RECORDS — an area's patrol types and its stations, and every
 * patrol already filed under one carried across to it.
 *
 * EXPAND → BACKFILL → CONTRACT, IN ONE VERSION, which is what makes this safe to
 * run on a populated installation: the two tables are created, filled from the
 * patrols themselves, the two foreign keys are added NULLABLE, matched, and only
 * then is the required one tightened. A failure anywhere leaves the whole thing
 * untouched and nobody edits a vendor file.
 *
 * WHY THE VOCABULARY IS READ OUT OF THE PATROLS AND NOT OUT OF `patrol.types`.
 * A migration runs against a database, not against a booted application: the
 * installation's configured types are not on offer here, and reaching for them
 * would make this version depend on a container it is not given. Reading the
 * DISTINCT type strings the area has actually used is also the stronger choice —
 * it is by construction a superset of whatever the config says, so EVERY patrol
 * matches a row and the NOT NULL below can never fail on somebody's data. An
 * installation running the shipped configuration gets exactly `foot`, `vehicle`
 * and `drone` out of it, because those are the words its patrols carry.
 *
 * A patrol whose type string is blank — which the column permits and nothing
 * writes — is filed under a type keyed `unspecified` rather than left behind, so
 * "every row matched" is a fact and not a hope. Nothing is skipped and nothing
 * is deleted.
 *
 * THE STATION KEY IS SLUGGED FROM THE STRING, made unique within the area with a
 * numeric suffix where two spellings slug alike, and the label is the string
 * exactly as it was typed — so the Settings section opens showing the words the
 * area already used.
 *
 * STATION STAYS NULLABLE, because a patrol that named no station is a real
 * patrol and always was.
 *
 * THE TWO STRING COLUMNS (`patrol_patrol.type`, `patrol_patrol.station`) ARE
 * DELIBERATELY LEFT IN PLACE. The code writes them from the relations for one
 * more release, so a rollback finds its values where it left them; the version
 * that drops them rides a LATER release and will carry the `@destructive`
 * marker in its class docblock.
 *
 * ITS DATE places it after this module's settings table and after every core
 * version, which is what lets the foreign keys name `area_of_interest`.
 *
 * @see vendor/uhifadhi/uhifadhi/src/Uhifadhi/Bundle/RegistryBundle/Version/VersionTimestampComparator.php
 */
final class Version20260911120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'The area\'s own patrol types and stations, with every existing patrol carried onto them.';
    }

    public function up(Schema $schema): void
    {
        // ── expand ────────────────────────────────────────────────────────────
        $this->addSql('CREATE TABLE patrol_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, type_key VARCHAR(40) NOT NULL, label VARCHAR(80) NOT NULL, position INT DEFAULT 0 NOT NULL, active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, area_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FDABAB67D17F50A6 ON patrol_type (uuid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_patrol_type_area_key ON patrol_type (area_id, type_key)');
        $this->addSql('CREATE INDEX IDX_FDABAB67BD0F409C ON patrol_type (area_id)');
        $this->addSql('ALTER TABLE patrol_type ADD CONSTRAINT FK_FDABAB67BD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE patrol_station (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, station_key VARCHAR(60) NOT NULL, label VARCHAR(80) NOT NULL, position INT DEFAULT 0 NOT NULL, active BOOLEAN DEFAULT true NOT NULL, point geometry(POINT,4326) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, area_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7D5B7308D17F50A6 ON patrol_station (uuid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_patrol_station_area_key ON patrol_station (area_id, station_key)');
        $this->addSql('CREATE INDEX IDX_7D5B7308BD0F409C ON patrol_station (area_id)');
        $this->addSql('CREATE INDEX idx_patrol_station_point_sp ON patrol_station USING gist (point)');
        $this->addSql('ALTER TABLE patrol_station ADD CONSTRAINT FK_7D5B7308BD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');

        // ── backfill the vocabulary out of the patrols themselves ─────────────
        $this->addSql(<<<'SQL'
            INSERT INTO patrol_type (uuid, area_id, type_key, label, position, active, created_at, updated_at)
            SELECT gen_random_uuid(),
                   d.area_id,
                   d.type_key,
                   INITCAP(REPLACE(REPLACE(d.type_key, '-', ' '), '_', ' ')),
                   ROW_NUMBER() OVER (PARTITION BY d.area_id ORDER BY d.type_key) - 1,
                   TRUE,
                   NOW(),
                   NOW()
            FROM (
                SELECT DISTINCT area_id, COALESCE(NULLIF(TRIM(type), ''), 'unspecified') AS type_key
                FROM patrol_patrol
            ) d
            SQL);

        $this->addSql(<<<'SQL'
            INSERT INTO patrol_station (uuid, area_id, station_key, label, position, active, created_at, updated_at)
            SELECT gen_random_uuid(),
                   s.area_id,
                   CASE WHEN s.n = 1 THEN s.base ELSE LEFT(s.base, 57) || '-' || s.n END,
                   s.label,
                   ROW_NUMBER() OVER (PARTITION BY s.area_id ORDER BY s.label) - 1,
                   TRUE,
                   NOW(),
                   NOW()
            FROM (
                SELECT t.area_id,
                       t.label,
                       t.base,
                       ROW_NUMBER() OVER (PARTITION BY t.area_id, t.base ORDER BY t.label) AS n
                FROM (
                    SELECT DISTINCT
                           area_id,
                           station AS label,
                           COALESCE(
                               NULLIF(TRIM(BOTH '-' FROM LEFT(TRIM(BOTH '-' FROM REGEXP_REPLACE(LOWER(station), '[^a-z0-9]+', '-', 'g')), 60)), ''),
                               'station'
                           ) AS base
                    FROM patrol_patrol
                    WHERE station IS NOT NULL AND TRIM(station) <> ''
                ) t
            ) s
            SQL);

        // ── the two keys, nullable first ──────────────────────────────────────
        $this->addSql('ALTER TABLE patrol_patrol ADD patrol_type_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE patrol_patrol ADD station_id INT DEFAULT NULL');

        $this->addSql(<<<'SQL'
            UPDATE patrol_patrol p
            SET patrol_type_id = t.id
            FROM patrol_type t
            WHERE t.area_id = p.area_id
              AND t.type_key = COALESCE(NULLIF(TRIM(p.type), ''), 'unspecified')
            SQL);

        $this->addSql(<<<'SQL'
            UPDATE patrol_patrol p
            SET station_id = s.id
            FROM patrol_station s
            WHERE s.area_id = p.area_id
              AND s.label = p.station
            SQL);

        // ── contract ──────────────────────────────────────────────────────────
        // Every row matched, by construction: the types were read out of these
        // very strings. The station key stays nullable — a patrol that named no
        // station always was one.
        $this->addSql('ALTER TABLE patrol_patrol ALTER patrol_type_id SET NOT NULL');

        $this->addSql('ALTER TABLE patrol_patrol ADD CONSTRAINT FK_D10A8EB8272E072A FOREIGN KEY (patrol_type_id) REFERENCES patrol_type (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_patrol ADD CONSTRAINT FK_D10A8EB821BDB235 FOREIGN KEY (station_id) REFERENCES patrol_station (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_D10A8EB8272E072A ON patrol_patrol (patrol_type_id)');
        $this->addSql('CREATE INDEX IDX_D10A8EB821BDB235 ON patrol_patrol (station_id)');
    }

    /**
     * @destructive — going back down drops the two vocabulary tables, and with
     *                them any type or station created since the upgrade. The
     *                two string columns this version deliberately left in place
     *                are what a patrol still reads back from, so no PATROL
     *                loses its words; the curation does.
     */
    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE patrol_patrol DROP CONSTRAINT FK_D10A8EB8272E072A');
        $this->addSql('ALTER TABLE patrol_patrol DROP CONSTRAINT FK_D10A8EB821BDB235');
        $this->addSql('DROP INDEX IDX_D10A8EB8272E072A');
        $this->addSql('DROP INDEX IDX_D10A8EB821BDB235');
        $this->addSql('ALTER TABLE patrol_patrol DROP patrol_type_id');
        $this->addSql('ALTER TABLE patrol_patrol DROP station_id');
        $this->addSql('ALTER TABLE patrol_station DROP CONSTRAINT FK_7D5B7308BD0F409C');
        $this->addSql('ALTER TABLE patrol_type DROP CONSTRAINT FK_FDABAB67BD0F409C');
        $this->addSql('DROP TABLE patrol_station');
        $this->addSql('DROP TABLE patrol_type');
    }
}
