<?php

declare(strict_types=1);

/*
 * This file is part of the UhifadhiLabs Patrol Module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Patrol\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * WHAT ONE AREA RUNS PATROLS ON — the table behind the module's Settings
 * section.
 *
 * A NEW TABLE, SO THERE IS NOTHING TO BACKFILL. The expand → backfill → contract
 * rule bites where a required column lands on a populated table; here the table
 * itself is new and starts empty, and empty is the correct starting state: an
 * area with no row reads the installation's configuration, so writing a row per
 * area now would turn every untouched default into a choice somebody made.
 *
 * ITS DATE PLACES IT after this module's first migration and after every core
 * version, which is what lets the foreign key name `area_of_interest`.
 *
 * @see vendor/uhifadhi/uhifadhi/src/Uhifadhi/Bundle/RegistryBundle/Version/VersionTimestampComparator.php
 */
final class Version20260911090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'The per-area patrol settings the module\'s Settings section writes.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE patrol_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, gap_threshold_minutes SMALLINT NOT NULL, discard_retention_days SMALLINT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, area_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_571AC966D17F50A6 ON patrol_settings (uuid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_patrol_settings_area ON patrol_settings (area_id)');
        $this->addSql('ALTER TABLE patrol_settings ADD CONSTRAINT FK_571AC966BD0F409C FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    /**
     * @destructive — dropping this table destroys every area's chosen numbers.
     *                It is the reverse of a migration that only ever added a
     *                table, so it is safe to run back down a release, and there
     *                is nothing else it could mean.
     */
    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE patrol_settings DROP CONSTRAINT FK_571AC966BD0F409C');
        $this->addSql('DROP TABLE patrol_settings');
    }
}
