<?php

declare(strict_types=1);

/*
 * This file is part of the UhifadhiLabs Patrol Module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Patrol\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * A PATROL BEING WRITTEN, and the source file the finished one keeps.
 *
 * The one entry flow takes the track and the photographs through the platform's
 * upload component on the way IN, which means files arrive before the patrol
 * they belong to exists. `patrol_draft` is what they arrive against — a row per
 * open form, carrying the area the permission is asked on and the person it
 * belongs to — and `patrol_draft_file` is what the upload contract's "write the
 * row" writes. Both are short-lived by construction: saving empties them, and
 * `patrol:purge-discarded` sweeps what nobody came back to.
 *
 * TWO NEW TABLES, SO THERE IS NOTHING TO BACKFILL. The expand → backfill →
 * contract rule bites where a required column lands on a populated table, and
 * empty is the correct starting state for both: a draft that exists is a form
 * somebody has open right now.
 *
 * THE THIRD CHANGE IS ONE NULLABLE COLUMN on a populated table, and it ships
 * nullable on purpose rather than being backfilled. `track_file_key` names the
 * GPX a patrol was recorded from, and only a patrol that came in through this
 * flow has one: every patrol recorded before it had its track parsed and its
 * bytes discarded, and a patrol written up by hand never had a file at all.
 * There is no universal value to write, so the column stays nullable and null
 * keeps meaning exactly what it says.
 *
 * ITS DATE PLACES IT after this module's other migrations and after every core
 * version, which is what lets the foreign keys name `area_of_interest` and
 * `team_user`.
 *
 * @see vendor/uhifadhi/uhifadhi/src/Uhifadhi/Bundle/RegistryBundle/Version/VersionTimestampComparator.php
 */
final class Version20260911160000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'The draft a patrol is written on, the files it receives, and the source track a saved patrol keeps.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE patrol_draft (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, area_id INT NOT NULL, owner_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D7698FFFD17F50A6 ON patrol_draft (uuid)');
        $this->addSql('CREATE INDEX IDX_D7698FFFBD0F409C ON patrol_draft (area_id)');
        $this->addSql('CREATE INDEX IDX_D7698FFF7E3C61F9 ON patrol_draft (owner_id)');
        // The sweep asks for drafts older than a cutoff and nothing else.
        $this->addSql('CREATE INDEX IDX_PATROL_DRAFT_CREATED ON patrol_draft (created_at)');
        $this->addSql('ALTER TABLE patrol_draft ADD CONSTRAINT FK_PATROL_DRAFT_AREA FOREIGN KEY (area_id) REFERENCES area_of_interest (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patrol_draft ADD CONSTRAINT FK_PATROL_DRAFT_OWNER FOREIGN KEY (owner_id) REFERENCES team_user (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql('CREATE TABLE patrol_draft_file (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slot VARCHAR(40) NOT NULL, storage_key VARCHAR(255) NOT NULL, thumb_key VARCHAR(255) DEFAULT NULL, mime_type VARCHAR(100) DEFAULT NULL, byte_size INT DEFAULT NULL, label VARCHAR(255) NOT NULL, outcome VARCHAR(120) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, draft_id INT NOT NULL, PRIMARY KEY (id))');
        // Bytes have one name, and a removal arrives holding nothing but it.
        $this->addSql('CREATE UNIQUE INDEX UNIQ_279B849D111795A5 ON patrol_draft_file (storage_key)');
        $this->addSql('CREATE INDEX IDX_279B849DE2F3C5D1 ON patrol_draft_file (draft_id)');
        $this->addSql('ALTER TABLE patrol_draft_file ADD CONSTRAINT FK_PATROL_DRAFT_FILE_DRAFT FOREIGN KEY (draft_id) REFERENCES patrol_draft (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('ALTER TABLE patrol_patrol ADD track_file_key VARCHAR(255) DEFAULT NULL');
    }

    /**
     * @destructive — going back down drops every form somebody has open and the
     *                files those forms had already received, and forgets where a
     *                saved patrol's source track is filed. The bytes themselves
     *                are not touched by SQL; a deployment rolling this back
     *                should run `patrol:purge-discarded` first, so the storage
     *                is swept while the rows that name it still exist.
     */
    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE patrol_patrol DROP track_file_key');
        $this->addSql('ALTER TABLE patrol_draft_file DROP CONSTRAINT FK_PATROL_DRAFT_FILE_DRAFT');
        $this->addSql('DROP TABLE patrol_draft_file');
        $this->addSql('ALTER TABLE patrol_draft DROP CONSTRAINT FK_PATROL_DRAFT_AREA');
        $this->addSql('ALTER TABLE patrol_draft DROP CONSTRAINT FK_PATROL_DRAFT_OWNER');
        $this->addSql('DROP TABLE patrol_draft');
    }
}
