<?php

declare(strict_types=1);

/*
 * This file is part of the UhifadhiLabs Patrol Module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Patrol\Tests\Unit;

use Uhifadhi\Bundle\AreaBundle\AreaBundle;
use Uhifadhi\Bundle\AtlasBundle\AtlasBundle;
use Uhifadhi\Bundle\ShellBundle\ShellBundle;
use Uhifadhi\Bundle\ShellBundle\Test\VocabularyConformanceTestCase;
use Uhifadhi\Storage\UhifadhiStorageBundle;

/**
 * THE PATROL SCREENS SPEND NO CLASS, TOKEN OR GLYPH NOBODY SHIPS.
 *
 * THE CHAIN IS THE SHEETS A PAGE ACTUALLY LINKS, in the order
 * templates/base.html.twig links them: the atlas's map chrome, the shell's
 * widget library sheet — the dashboard IS a widget surface, so every page links
 * that one — the file-preview overlay's, the area's, whose overview page renders
 * this module's six contributions, and then this module's own two, last because
 * they are the ones allowed to decorate. Leaflet's own sheet is left
 * out: it is a vendored library rather than a vocabulary, and its selectors are
 * generated by the script that builds the map.
 *
 * @see VocabularyConformanceTestCase
 */
final class VocabularyConformanceTest extends VocabularyConformanceTestCase
{
    protected static function bundlePath(): string
    {
        return \dirname(__DIR__, 2);
    }

    protected static function alias(): string
    {
        return 'patrol';
    }

    /**
     * Two: the module's own vocabulary, and the observation-taxonomy admin's,
     * which is the one screen that links a second sheet of its own.
     *
     * @return list<string>
     */
    protected static function ownStylesheets(): array
    {
        return ['patrol.css', 'taxonomy.css'];
    }

    /** @return list<string> */
    protected static function linkedStylesheets(): array
    {
        return [
            ...parent::linkedStylesheets(),
            self::publicDirOf(ShellBundle::class).'/widget.css',
            self::publicDirOf(AtlasBundle::class).'/map.css',
            // The six overview partials are rendered by AreaBundle's own
            // overview page, which links that bundle's sheet beside this one.
            self::publicDirOf(AreaBundle::class).'/area.css',
            // The storage bundle's class sits under src/, so its public/ is one
            // level further up than a core bundle's.
            self::publicDirOf(UhifadhiStorageBundle::class, 2).'/preview.css',
        ];
    }

    /**
     * THE MODULE DRAWS NO MAP OF ITS OWN.
     *
     * Every map on the platform is the atlas's plate: a module states what is on
     * it in PHP and calls render_map(), which mounts one controller and links one
     * Leaflet. A module template that names a map controller of its own, or
     * reaches for Leaflet directly, has started a second answer to a settled
     * question — a map that looks and behaves unlike every other map in the
     * product, and, with Leaflet, a second module namespace whose layers the
     * real map refuses.
     */
    public function testNoTemplateDrawsAMapOfItsOwn(): void
    {
        $offenders = [];
        foreach (self::templateFiles() as $file) {
            // What a template EMITS, so a comment explaining where the map comes
            // from is not read as a map.
            $markup = (string) preg_replace('/\{#.*?#\}/s', '', (string) file_get_contents($file));
            $name = basename($file);

            if (preg_match('/data-controller="[^"]*(map|plate)[^"]*"/i', $markup, $matches)
                && !str_contains($matches[0], 'atlas-bundle--map-plate')) {
                $offenders[] = $name.': '.$matches[0];
            }

            // The atlas's own stylesheet constant names the sheet, not the
            // library; anything else spelling "leaflet" is reaching past the
            // plate for the map itself.
            if (preg_match('/leaflet/i', $markup)) {
                $offenders[] = $name.': leaflet';
            }
        }

        self::assertSame([], $offenders, 'a module draws no map of its own: state it in PHP and call render_map()');
    }

    /**
     * @return list<string>
     */
    private static function templateFiles(): array
    {
        $files = [];
        $directory = new \RecursiveDirectoryIterator(self::bundlePath().'/templates', \FilesystemIterator::SKIP_DOTS);
        /** @var \SplFileInfo $file */
        foreach (new \RecursiveIteratorIterator($directory) as $file) {
            if ($file->isFile() && str_ends_with($file->getFilename(), '.html.twig')) {
                $files[] = $file->getPathname();
            }
        }

        sort($files);

        return $files;
    }

    /**
     * @param class-string $bundle
     * @param int<1, max>  $levels
     */
    private static function publicDirOf(string $bundle, int $levels = 1): string
    {
        return \dirname(new \ReflectionClass($bundle)->getFileName() ?: '', $levels).'/public';
    }
}
